### ISSUE TITLE
Dataset and setup problems

### ISSUE THREAD

**Issue by Jhih-Ciang** [tianyu0207/weakly-polyp#3]
Thanks for your great work. The dataset downloaded from the link is unzippable. Besides, can you provide the details of the setup for experiment? Thanks for your reply.

**Comment by tianyu0207** [comment]
> reply

Hi Thanks for your interest in our work. The dataset has been reuploaded into google drive.

**Comment by tianyu0207** [comment]
> dataset



> Thanks for your great work. The dataset downloaded from the link is unzippable. Besides, can you provide the details of the setup for experiment? Thanks for your reply.

The dataset and the i3d features has been uploaded in the repo. Please use the data features as the train and testing set because the raw videos are not consistent with the paper. Meanwhile, you could select the videos accordingly based on the feature filename. Then you are able to extract the features using strong video classifiers.
